### ISSUE TITLE
Contributor known only by VIAF crashes metadata.apply()

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/server_core#151]
You can see this by running `bin/identifiers_resolve "3M ID" kob6t89` on metadata.

```
  File "/home/leonardr/refactored/metadata/core/metadata_layer.py", line 1171, in update_contributions
    _db, self.identifiers, metadata_client
  File "/home/leonardr/refactored/metadata/core/metadata_layer.py", line 174, in find_sort_name
    "Cannot find sort name for a contributor with no display name!"
ValueError: Cannot find sort name for a contributor with no display name!
```

One of the contributors turns up with a VIAF number but no name. In theory this is nothing we can't handle, since we can look up name given VIAF. But the code as written crashes.

**Comment by courte** [comment]
This has been resolved by NYPL-Simplified/metadata_wrangler#88.
