### ISSUE TITLE
Edition.author ends up empty for works that are compilations or translations

### ISSUE THREAD

**Issue by gwendolen** [NYPL-Simplified/server_core#18]
_From @leonardr on August 20, 2015 16:3_

A large number of works have an editor, or a translator, but no 'author' per se. The Edition.author field ends up empty for such works, when it should end up something like 'Mallory Eve (ed.)" or "Alice Roberts (trans.)" or "Bob Bloggs (dir.)".

This is very common among Overdrive books, since Overdrive is very particular about listing editors and translators as such, not as authors.

Fixing this requires a fix in the metadata wrangler, and then refreshing all affected works in the circulation manager.

_Copied from original issue: NYPL/Simplified-iOS#211_

**Comment by leonardr** [comment]
I am pretty sure this problem has been solved. Editors and translators show up as 'authors' in the OPDS feed presented to patrons.
