### ISSUE TITLE
Instead of merging works, delete the old one and move in its licensepools

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/server_core#240]
We have some complex logic for merging two Works upon discovery that they represent the same literary work. This logic isn't really necessary anymore because patrons never interact directly with a work, only with the LicensePools or the Identifiers associated with that work.

So, let's try getting rid of Work.merged_into_id and changing the merge code to move over the LicensePools and just delete the old work.

**Comment by aslagle** [comment]
I got rid of the merge code entirely and wrote a migration to delete any works that were previously merged.
