### ISSUE TITLE
Adobe DRM media type is wrong

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/server_core#352]
```
ADOBE_DRM = "vnd.adobe/adept+xml"
```

Should be `application/vnd.adobe.adept+xml`. This was my stupid mistake.

Unfortunately we (probably) can't just change this. The clients need to be changed to look for the correct media type. Old clients still need to be supported.

The first step is probably to start serving the DeliveryMechanism under both the incorrect media type and the correct media type. Then we fix the clients, then (after waiting for everyone to update) we remove the incorrect media type.

**Comment by leonardr** [comment]
@winniequinn has confirmed that just changing the media type will not break iOS clients. We still need to check whether that is true for Android clients.

**Comment by winniequinn** [comment]
@aferditamuriqi Have we confirmed that this is okay on Android?
