### ISSUE TITLE
UnfulfillableWork exception makes OPDS feed that's not a valid acquisition feed

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/server_core#371]
When there's an UnfulfillableWork exception we create an entry with an "I know about this work but can offer no way of fulfilling it" message. Since the entry has no acquisition link, the feed isn't a valid OPDS acquisition feed. This is a problem for the web client because it thinks it's a navigation feed.

**Comment by leonardr** [comment]
We discussed this and decided that it was an abuse of OPDS to use the `<entry>` tag to convey custom messages. We're going to switch to use a custom `<simplified:message>` tag instead. This will require changing opds_import.py as well as the code that generates OPDS feeds.
