### ISSUE TITLE
Migration only works for Postgres 9.5+

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/server_core#380]
This may or may not be a problem worth dealing with, but in `migration/20160804-circulation-event-index.sql`, the syntax `CREATE INDEX IF NOT EXISTS` only works with Postgres 9.5 so the last two lines raise errors on earlier versions.

We've had folks with 9.2 or 9.3 in the past and recommended updating -- should we expect version updates on the database level or alter migrations to be backwards compatible?

**Comment by leonardr** [comment]
Our production circulation manager is only running on 9.4, so it is pretty important. I've run that migration script on our production servers and as I did so I modified it to work on 9.4.
