### ISSUE TITLE
"Short stories" does not behave like other genres

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/server_core#425]
The "Short Stories" genre tends to be excluded by other genres like "Romance" and "Literary Fiction". This doesn't make sense. A title that's 80% Romance and 20% Science Fiction can be safely classified under Romance and not Science Fiction. But a title is either a short story or it's not. If it's 80% Romance and 20% Short Story, it should _at least_ be filed under both categories, and possibly only filed under Short Stories. It depends on the collection, but the fact that a story falls into a literary genre generally doesn't mean you shouldn't file it with the other short stories.

I can think of two ways to handle this. The first is to make Short Stories non-rivalrous with the other genres. If a title meets a certain threshold of Short Story-ness, it gets the Short Stories WorkGenre, Short Stories is removed from consideration, and _then_ we apply the normal WorkGenre assignment algorithm.

The other solution is to treat length not as a genre, but as an independent feature of a Work alongside fiction status and audience. This would mean adding a field to Subject and Work. It should be really easy to determine the length, especially if we say that short story _collections_ get filed under "short" along with individual shorts.

The second solution is nicer but it seems like a lot of work for relatively little benefit. The only time we'd really need it is if we wanted a lane that excluded shorts.

**Comment by courte** [comment]
Specific to the FeedBooks works (which may have prompted this issue), I believe this was resolved using the first method by Simplified/server_core#451. And excluding genres like "Short Stories" from a lane without specifying an overall lane genre became possible in NYPL-Simplified/server_core#457.
