### ISSUE TITLE
Most unglue.it books are not imported

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/server_core#63]
The first page of an unglue.it feed links to another copy of the first page of the feed. (I've notified Eric of this.) This wouldn't be a problem except for the code that makes sure we stop importing from an OPDS feed when we encounter a page full of books we've already imported. The combination of these two things mean we will only ever import the first page of books.

We can solve this by keeping track of which books we imported on _the current import_. Those books won't count if we encounter them again--we'll plow on through to the 'third' page (actually the second) and keep going.

**Comment by aslagle** [comment]
Looks like this has been fixed in unglue.it
