### ISSUE TITLE
Allow books to be returned without requiring the book downloaded

### ISSUE THREAD

**Issue by dehunt** [NYPL-Simplified/server_core#727]
Currently a book can only be returned after it's been downloaded.

It would be a minor convenience if there was a way to return books without requiring a download.

This was suggested after discovering that a book cannot be returned when an account has reached the Adobe Device Limit, because the book cannot be downloaded.

@gioneill

**Comment by leonardr** [comment]
This is a mobile issue. I've re-filed it in the iOS project: https://github.com/NYPL-Simplified/Simplified-iOS/issues/882
